import type { Metadata } from 'next';
import { Comic_Neue, Satisfy } from 'next/font/google';
import './globals.css';
import { NextUIProvider } from '@nextui-org/react';
import ResponsiveNavbar from '../components/ResponsiveNavbar';

const comicNeue = Comic_Neue({ weight: '400', subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={comicNeue.className}>
        <NextUIProvider>
          <ResponsiveNavbar
            items={[
              { name: 'Adopt', href: 'adopt' },
              { name: 'About', href: 'about' },
              { name: 'Contact', href: 'contact' },
            ]}
          />
          {children}
        </NextUIProvider>
      </body>
    </html>
  );
}
